name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Clean old app on VM
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            rm -rf /home/azureuser/app
            mkdir -p /home/azureuser/app
          "

      - name: Copy project to VM
        run: |
          scp -i ~/.ssh/id_rsa -r * ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/azureuser/app

      - name: Install & Run App
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd /home/azureuser/app
            sudo pkill node || true
            sudo apt update -y
            sudo apt install -y nodejs npm
            npm install
            sudo nohup node app.js > app.log 2>&1 &
          "
